[project]
name = 'stable-clar'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.user_entry]
path = 'contracts/user_entry.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[contracts.ft-trait]
path = 'contracts/traits/ft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.oracle-trait]
path = 'contracts/traits/oracle-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.simple_oracle]
path = 'contracts/oracles/simple_oracle.clar'
clarity_version = 2
epoch = 2.4

[contracts.ownable-trait]
path = 'contracts/traits/ownable-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = 'contracts/mocks/sbtc.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
