[project]
name = 'stable-clar'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.user-entry]
path = 'contracts/user-entry.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[contracts.ft-trait]
path = 'contracts/traits/ft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.oracle-trait]
path = 'contracts/traits/oracle-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.position-storage-trait]
path = 'contracts/traits/position-storage-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.simple-oracle]
path = 'contracts/oracles/simple-oracle.clar'
clarity_version = 2
epoch = 2.4

[contracts.position-storage]
path = 'contracts/storages/position-storage.clar'
clarity_version = 2
epoch = 2.4

[contracts.config-storage]
path = 'contracts/storages/config-storage.clar'
clarity_version = 2
epoch = 2.4

[contracts.ownable-trait]
path = 'contracts/traits/ownable-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = 'contracts/mocks/sbtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.fake-simple-oracle]
path = 'contracts/mocks/fake-simple-oracle.clar'
clarity_version = 2
epoch = 2.4

[contracts.fake-position-storage]
path = 'contracts/mocks/fake-position-storage.clar'
clarity_version = 2
epoch = 2.4

[contracts.fake-sbtc]
path = 'contracts/mocks/fake-sbtc.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
